// The desktop theme is lib/theme/theme.css, read at build time — never a
// hand-copied palette. This pulls the v5 custom properties for light (the
// first :root block) and dark (:root[data-theme="dark"]) into a generated
// table, and unpacks the vendored WOFF2 faces (Inter, Newsreader, IBM Plex
// Mono) into TrueType, which is what the platform text systems load.
use base64::Engine as _;
use std::{env, fmt::Write as _, fs, path::PathBuf};

fn block<'a>(css: &'a str, opener: &str) -> &'a str {
    let start = css.find(opener).unwrap_or_else(|| panic!("theme.css: no {opener}")) + opener.len();
    let end = start + css[start..].find('}').expect("theme.css: unclosed block");
    &css[start..end]
}

fn props(body: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    // strip comments, then split declarations
    let mut clean = String::new();
    let mut rest = body;
    while let Some(i) = rest.find("/*") {
        clean.push_str(&rest[..i]);
        rest = rest[i..].find("*/").map(|j| &rest[i + j + 2..]).unwrap_or("");
    }
    clean.push_str(rest);
    for decl in clean.split(';') {
        let decl = decl.trim();
        if let Some(d) = decl.strip_prefix("--") {
            if let Some((k, v)) = d.split_once(':') {
                out.push((k.trim().to_string(), v.trim().to_string()));
            }
        }
    }
    out
}

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let css_path = manifest.join("../../lib/theme/theme.css");
    println!("cargo:rerun-if-changed={}", css_path.display());
    let css = fs::read_to_string(&css_path).expect("read lib/theme/theme.css");
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());

    let light = props(block(&css, ":root {"));
    let dark = props(block(&css, ":root[data-theme=\"dark\"] {"));
    assert!(light.iter().any(|(k, _)| k == "paper"), "theme.css: light tokens not found");
    assert!(dark.iter().any(|(k, _)| k == "paper"), "theme.css: dark tokens not found");

    let mut src = String::from("// @generated by build.rs from lib/theme/theme.css\n");
    for (name, set) in [("LIGHT", &light), ("DARK", &dark)] {
        writeln!(src, "pub const {name}: &[(&str, &str)] = &[").unwrap();
        for (k, v) in set.iter() {
            writeln!(src, "    ({k:?}, {v:?}),").unwrap();
        }
        writeln!(src, "];").unwrap();
    }

    // @font-face { font-family: "X"; font-weight: N[ M]; src: url(data:font/woff2;base64,...) }
    let fonts_dir = out.join("fonts");
    fs::create_dir_all(&fonts_dir).unwrap();
    writeln!(src, "pub const FONTS: &[(&str, &[u8])] = &[").unwrap();
    let mut rest = css.as_str();
    let mut n = 0;
    while let Some(i) = rest.find("@font-face") {
        let face = &rest[i..];
        let end = face.find('}').unwrap();
        let face_body = &face[..end];
        rest = &face[end..];
        let family = face_body
            .split("font-family:")
            .nth(1)
            .and_then(|s| s.split(';').next())
            .map(|s| s.trim().trim_matches('"').to_string())
            .expect("font-face without family");
        let weight = face_body
            .split("font-weight:")
            .nth(1)
            .and_then(|s| s.split(';').next())
            .map(|s| s.trim().replace(' ', "-"))
            .unwrap_or_else(|| "400".into());
        let style = face_body
            .split("font-style:")
            .nth(1)
            .and_then(|s| s.split(';').next())
            .map(|s| s.trim().to_string())
            .unwrap_or_else(|| "normal".into());
        let Some(b64) = face_body.split("base64,").nth(1).and_then(|s| s.split(')').next()) else {
            continue;
        };
        let woff2 = base64::engine::general_purpose::STANDARD.decode(b64.trim()).expect("font base64");
        let ttf = wuff::decompress_woff2(&woff2).expect("woff2 decode");
        let file = format!("{}-{}-{}.ttf", family.replace(' ', ""), weight, style);
        fs::write(fonts_dir.join(&file), ttf).unwrap();
        writeln!(src, "    ({family:?}, include_bytes!(concat!(env!(\"OUT_DIR\"), \"/fonts/{file}\"))),").unwrap();
        n += 1;
    }
    writeln!(src, "];").unwrap();
    assert!(n >= 3, "theme.css: expected the vendored faces, found {n}");
    fs::write(out.join("theme_tokens.rs"), src).unwrap();
}
